### ISSUE TITLE
Bot is missing permissions in server

### ISSUE THREAD

**Issue by UncleDave** [UncleDave/DiscordSoundboardBot#57]
Bot crashes when attempting to leave the channel, both when he's the only one left in it or by using the `/disconnect` command.

```
2022-06-13T22:37:25.060991247Z 2022-06-14 00:37:25.060 error:    uncaughtException: Missing Permissions
2022-06-13T22:37:25.061018147Z DiscordAPIError: Missing Permissions
2022-06-13T22:37:25.061023947Z     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
2022-06-13T22:37:25.061028147Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-06-13T22:37:25.061032347Z     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
2022-06-13T22:37:25.061036348Z     at async GuildMemberManager.edit (/app/node_modules/discord.js/src/managers/GuildMemberManager.js:279:15)
```

I _suspect_ the bot just has the wrong permissions in the server and no code needs to change, as this worked on the dev bot last time I checked. Would be a good idea to review the permissions he needs and document them.

**Comment by stuckinab0x** [comment]
He needs `Voice Channel Permissions -> Move Members`. I've added it to his role. The only reason the dev bots didn't have this problem is because `Default Permissions` has `Administrator`. 😝 

I'll leave this open in tho case you want to TODO making a list of what he actually uses.

**Comment by stuckinab0x** [comment]
Let's make this ded, I can test to see what perms we actually use, do you wanna throw them in a notepad somewhere or somewhere more formal?

**Comment by UncleDave** [comment]
I was thinking just slap em in README.md
